# Generated by Django 2.1.7 on 2019-04-05 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_name', models.CharField(max_length=30, verbose_name='Ability Name')),
                ('ability_desc', models.CharField(max_length=300, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Ability')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(verbose_name='Date Added')),
                ('type_primary', models.CharField(choices=[('0', 'Normal'), ('1', 'Fire'), ('2', 'Fighting'), ('3', 'Water'), ('4', 'Grass'), ('5', 'Flying'), ('6', 'Poison'), ('7', 'Electric'), ('8', 'Ground'), ('9', 'Psychic'), ('10', 'Rock'), ('11', 'Ice'), ('12', 'Bug'), ('13', 'Dragon'), ('14', 'Ghost'), ('15', 'Dark'), ('16', 'Steel'), ('17', 'Fairy'), ('18', 'Cyber')], default='Normal', max_length=10)),
                ('type_secondary', models.CharField(blank=True, choices=[('0', 'Normal'), ('1', 'Fire'), ('2', 'Fighting'), ('3', 'Water'), ('4', 'Grass'), ('5', 'Flying'), ('6', 'Poison'), ('7', 'Electric'), ('8', 'Ground'), ('9', 'Psychic'), ('10', 'Rock'), ('11', 'Ice'), ('12', 'Bug'), ('13', 'Dragon'), ('14', 'Ghost'), ('15', 'Dark'), ('16', 'Steel'), ('17', 'Fairy'), ('18', 'Cyber')], default=None, max_length=10, null=True)),
                ('max_height', models.FloatField(default='0', max_length=10)),
                ('min_height', models.FloatField(default='0', max_length=10)),
                ('max_weight', models.FloatField(default='0', max_length=10)),
                ('min_weight', models.FloatField(default='0', max_length=10)),
                ('egg_group_1', models.CharField(choices=[('0', 'Monster'), ('1', 'Human-Like'), ('2', 'Bug'), ('3', 'Water 1'), ('4', 'Water 2'), ('5', 'Water 3'), ('6', 'Mineral'), ('7', 'Flying'), ('8', 'Amorphous'), ('9', 'Field'), ('10', 'Fairy'), ('11', 'Ditto'), ('12', 'Grass'), ('13', 'Dragon'), ('14', 'Undiscovered'), ('15', 'Gender unknown')], default='Undiscovered', max_length=10)),
                ('egg_group_2', models.CharField(blank=True, choices=[('0', 'Monster'), ('1', 'Human-Like'), ('2', 'Bug'), ('3', 'Water 1'), ('4', 'Water 2'), ('5', 'Water 3'), ('6', 'Mineral'), ('7', 'Flying'), ('8', 'Amorphous'), ('9', 'Field'), ('10', 'Fairy'), ('11', 'Ditto'), ('12', 'Grass'), ('13', 'Dragon'), ('14', 'Undiscovered'), ('15', 'Gender unknown')], default=None, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='availableability',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Species'),
        ),
        migrations.AlterUniqueTogether(
            name='availableability',
            unique_together={('species', 'slot')},
        ),
    ]
