# Generated by Django 2.1.7 on 2019-04-05 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='ability_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ability_1', to='pokemon.Ability'),
        ),
        migrations.AddField(
            model_name='species',
            name='ability_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ability_2', to='pokemon.Ability'),
        ),
        migrations.AddField(
            model_name='species',
            name='ability_hidden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ability_hidden', to='pokemon.Ability'),
        ),
    ]
