# Generated by Django 2.1.7 on 2019-04-05 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_auto_20190405_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='ability_hidden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_ability', to='pokemon.Ability'),
        ),
    ]
