# Generated by Django 2.1.7 on 2019-04-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20190405_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='ability_hidden',
            new_name='hidden_ability',
        ),
    ]
