# Generated by Django 2.1.7 on 2019-04-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_auto_20190405_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': None},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': None},
        ),
    ]
