# Generated by Django 2.1.7 on 2019-04-05 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_auto_20190405_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'Ability'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Ability'},
        ),
    ]
