# Generated by Django 2.1.7 on 2019-04-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_auto_20190405_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'Abilities'},
        ),
    ]
