# Generated by Django 2.1.7 on 2019-04-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_auto_20190405_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='base_Attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='base_Defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='base_HP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='base_SpAttack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='base_SpDefense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='base_Speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='form',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='regional_variant',
            field=models.CharField(blank=True, choices=[('0', 'Alolan'), ('1', 'Unovan'), ('2', 'Sinnoan'), ('3', 'Galarian'), ('4', 'Zea'), ('5', 'Qinese')], default=None, max_length=10, null=True),
        ),
    ]
