# Generated by Django 2.1.7 on 2019-04-10 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_auto_20190410_1303'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='species',
            unique_together={('species_name', 'regional_variant', 'form')},
        ),
    ]
