# Generated by Django 2.1.7 on 2019-04-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0011_auto_20190410_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='form',
            field=models.CharField(blank=True, default='Base', max_length=10, null=True),
        ),
    ]
