# Generated by Django 2.1.7 on 2019-04-18 06:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0013_auto_20190410_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnableMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('0', 'Levelup'), ('1', 'TM'), ('2', 'Hatch'), ('3', 'Tutor')], default='TM', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_name', models.CharField(max_length=30, verbose_name='Move Name')),
                ('move_desc', models.CharField(max_length=300, verbose_name='Description')),
                ('move_type', models.CharField(choices=[('0', 'Normal'), ('1', 'Fire'), ('2', 'Fighting'), ('3', 'Water'), ('4', 'Grass'), ('5', 'Flying'), ('6', 'Poison'), ('7', 'Electric'), ('8', 'Ground'), ('9', 'Psychic'), ('10', 'Rock'), ('11', 'Ice'), ('12', 'Bug'), ('13', 'Dragon'), ('14', 'Ghost'), ('15', 'Dark'), ('16', 'Steel'), ('17', 'Fairy'), ('18', 'Cyber')], default='Normal', max_length=10)),
                ('base_power', models.IntegerField(verbose_name='Base Power')),
                ('base_accuracy', models.IntegerField(verbose_name='Accuracy')),
                ('move_category', models.CharField(choices=[('0', 'Status'), ('1', 'Physical'), ('2', 'Special')], default='Physical', max_length=8)),
                ('TM_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelMove',
            fields=[
                ('learnablemove_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pokemon.LearnableMove')),
                ('level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
            bases=('pokemon.learnablemove',),
        ),
        migrations.AddField(
            model_name='learnablemove',
            name='move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.Move'),
        ),
        migrations.AddField(
            model_name='learnablemove',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.Species'),
        ),
        migrations.AlterUniqueTogether(
            name='learnablemove',
            unique_together={('move', 'species', 'source')},
        ),
    ]
