# Generated by Django 2.1.7 on 2019-04-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0015_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('0', 'Alolan'), ('1', 'Unovan'), ('2', 'Sinnoan'), ('3', 'Galarian'), ('4', 'Zea'), ('5', 'Qinese')], default='Kanto', max_length=10),
        ),
    ]
