# Generated by Django 2.2.3 on 2019-07-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0016_auto_20190418_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('0', 'Kanto'), ('1', 'Johto'), ('2', 'Hoenn'), ('3', 'Sinnoh'), ('4', 'Unova'), ('5', 'Kalos'), ('6', 'Alola'), ('7', 'Galar'), ('8', 'Qinoa'), ('9', 'Zan')], default='Kanto', max_length=10),
        ),
        migrations.AlterField(
            model_name='move',
            name='base_accuracy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Accuracy'),
        ),
        migrations.AlterField(
            model_name='move',
            name='base_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Base Power'),
        ),
    ]
